-- ldoc configuration file
title = "ggram documentation"
description = "ggram – Telegram Bot Framework written on Lua"
project = "ggram"
-- one = true
-- no_summary = true
examples = {'examples', exclude = {}}

readme = {
    'readme.md',
    'info/development_tips.md',
    'info/making_extensions.md',
    'info/running_within_garrysmod.md',
    'info/troubleshooting.md',
    'info/understanding_things.md'
}

format = 'markdown'
