# Эта версия LuaJit используется в прогрессивной БД Tarantool, который заточен на производительность
# Здесь есть встроенный профайлер памяти: https://www.tarantool.io/en/doc/latest/reference/tooling/luajit_memprof/
# и функции для получения метрик компилятора: https://www.tarantool.io/ru/doc/latest/reference/tooling/luajit_getmetrics/

# BUILDING:
# docker build -t ggramdevenv -f Dockerfile_tarantool .

# misc.memprof.start() doesn't work on the Alpine
# https://github.com/tarantool/tarantool/issues/7899
FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y \
    git \
    cmake \
    make \
    gcc \
    g++ \
    libc6-dev \
    curl \
    tar \
    unzip \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Сборка LuaJIT
RUN set -eux \
    && LVP=/usr \
    && cd /tmp \
    && git clone https://github.com/tarantool/luajit.git \
    && mkdir luajit-build && cd luajit-build \
    && cmake ../luajit -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=$LVP \
    && cmake --build . --parallel \
    && make install \
    && cd /tmp && rm -rf luajit luajit-build

# Сборка LuaRocks
RUN set -eux \
    && LVP=/usr \
    && cd /tmp \
    && curl -L https://luarocks.org/releases/luarocks-3.11.1.tar.gz -o luarocks-3.11.1.tar.gz \
    && tar zxpf luarocks-3.11.1.tar.gz && rm luarocks-3.11.1.tar.gz \
    && cd luarocks-3.11.1 \
    && ln -s /usr/bin/luajit /usr/bin/lua \
    && ./configure --with-lua=$LVP --with-lua-include=$LVP/include/luajit-2.1 --with-lua-interpreter=luajit \
    && make && make install \
    && cd /tmp && rm -rf luarocks-3.11.1

# Установка пакетов через LuaRocks
RUN set -eux \
    && luarocks install copas \
    && luarocks install luasec \
    && luarocks install lua-cjson \
    && luarocks install lua-requests-async \
    && luarocks install lua-gmod-lib

# Удаляем ненужные пакеты для минимизации образа
RUN apt-get purge -y \
    git \
    cmake \
    make \
    gcc \
    g++ \
    curl \
    unzip \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

